project:
  type: website
  output-dir: docs

website:
  title: "Group Two"
  navbar:
    right:
      - href: index.qmd
        text: ABOUT US
      - data.qmd
      - Final Project.qmd
      - references.qmd
      - Final Code.qmd

format:
  html:
    theme:
      - minty
    toc: true


